# Generated by Django 4.2.8 on 2023-12-10 08:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="active"),
        ),
    ]
