# Generated by Django 4.2.8 on 2023-12-10 08:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_movie_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="slug",
            field=models.SlugField(default="a", unique=True),
            preserve_default=False,
        ),
    ]
