# Generated by Django 4.2.8 on 2023-12-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_movie_release_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="description",
            field=models.TextField(),
        ),
    ]
